import PageHero from '@/components/ui/PageHero'; import SectionHeader from '@/components/ui/SectionHeader'; import CapabilityGrid,{Capability} from '@/components/ui/CapabilityGrid';
import { createPageMetadata } from '@/lib/seo';
export const metadata = createPageMetadata({ title: 'Green Energy Solutions', description: 'Solar PV, hybrid power, battery energy storage, microgrids, energy audits and lifecycle support from GNIT.', path: '/services/green-energy', keywords: ['solar PV Nigeria', 'battery energy storage Nigeria', 'hybrid power systems', 'energy audit'] });
const items:Capability[]=[
  {title:'Solar PV Systems',description:'Grid-tied, off-grid and hybrid solar systems engineered for reliable performance.',image:'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&q=95&w=1800',imageAlt:'Commercial photovoltaic solar panels in operation'},
  {title:'Hybrid Power Systems',description:'Integrated solar, battery and generator systems for continuous, efficient power.',image:'/images/capabilities/hybrid-power-system.png',imageAlt:'Commercial hybrid power installation with solar panels, wind turbine, inverter and battery system'},
  {title:'Battery Energy Storage',description:'Scalable battery storage for resilience, peak-load management and backup capacity.',image:'/images/capabilities/commercial-battery-storage.png',imageAlt:'Commercial hybrid inverter and lithium battery energy storage system'},
  {title:'Commercial & Industrial Energy',description:'Renewable energy infrastructure designed around operational demand and return on investment.',image:'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&q=95&w=1800',imageAlt:'Industrial-scale solar power installation'},
  {title:'Microgrid Solutions',description:'Integrated generation, storage and control systems for resilient local power networks.',image:'https://images.unsplash.com/photo-1735571919545-5bbfd52b8f3d?auto=format&fit=crop&q=95&w=1800',imageAlt:'Electrical distribution equipment supporting a resilient local power network'},
  {title:'Energy Audits',description:'Site assessments that identify efficiency improvements and reduce energy cost.',image:'/images/capabilities/energy-system-audit.png',imageAlt:'Energy engineer carrying out a commercial solar and electrical system audit'},
  {title:'Operations & Maintenance',description:'Preventive maintenance, monitoring and responsive lifecycle support.',image:'/images/capabilities/energy-operations-maintenance.png',imageAlt:'Technicians performing preventive maintenance on a solar and battery installation'},
];
export default function GreenEnergy(){return <><PageHero badge="GREEN ENERGY" title="Renewable Energy Built For Performance." description="Solar PV, hybrid power systems, battery energy storage and energy audits."/><section className="section bg-[#F8FAFC]"><div className="container"><SectionHeader badge="CAPABILITIES" title="Green Energy Solutions" description="Complete engineering, procurement, installation and lifecycle support for clean energy infrastructure." center/><CapabilityGrid items={items}/></div></section></>}
