import PageHero from '@/components/ui/PageHero'; import SectionHeader from '@/components/ui/SectionHeader'; import CapabilityGrid,{Capability} from '@/components/ui/CapabilityGrid';
const items:Capability[]=[
  {title:'Solar PV Systems',description:'Grid-tied, off-grid and hybrid solar systems engineered for reliable performance.',image:'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&q=95&w=1800',imageAlt:'Commercial photovoltaic solar panels in operation'},
  {title:'Hybrid Power Systems',description:'Integrated solar, battery and generator systems for continuous, efficient power.',image:'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&q=95&w=1800',imageAlt:'Utility-scale renewable generation for hybrid power systems'},
  {title:'Battery Energy Storage',description:'Scalable battery storage for resilience, peak-load management and backup capacity.',image:'https://images.unsplash.com/photo-1605191737662-98ba90cb953e?auto=format&fit=crop&q=95&w=1800',imageAlt:'Battery module being installed in an energy storage cabinet'},
  {title:'Commercial & Industrial Energy',description:'Renewable energy infrastructure designed around operational demand and return on investment.',image:'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&q=95&w=1800',imageAlt:'Industrial-scale solar power installation'},
  {title:'Microgrid Solutions',description:'Integrated generation, storage and control systems for resilient local power networks.',image:'https://images.unsplash.com/photo-1735571919545-5bbfd52b8f3d?auto=format&fit=crop&q=95&w=1800',imageAlt:'Electrical distribution equipment supporting a resilient local power network'},
  {title:'Energy Audits',description:'Site assessments that identify efficiency improvements and reduce energy cost.',image:'https://images.unsplash.com/photo-1758101755915-462eddc23f57?auto=format&fit=crop&q=95&w=1800',imageAlt:'Electrician testing an electrical panel during an energy assessment'},
  {title:'Operations & Maintenance',description:'Preventive maintenance, monitoring and responsive lifecycle support.',image:'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&q=95&w=1800',imageAlt:'Technician maintaining critical electrical equipment'},
];
export default function GreenEnergy(){return <><PageHero badge="GREEN ENERGY" title="Renewable Energy Built For Performance." description="Solar PV, hybrid power systems, battery energy storage and energy audits."/><section className="section bg-[#F8FAFC]"><div className="container"><SectionHeader badge="CAPABILITIES" title="Green Energy Solutions" description="Complete engineering, procurement, installation and lifecycle support for clean energy infrastructure." center/><CapabilityGrid items={items}/></div></section></>}
