import PageHero from '@/components/ui/PageHero'; import SectionHeader from '@/components/ui/SectionHeader'; import CapabilityGrid,{Capability} from '@/components/ui/CapabilityGrid';
const items:Capability[]=[
  {title:'Enterprise Networking',description:'Resilient LAN, WAN and network security designed for critical operations.',image:'https://images.unsplash.com/photo-1695668548342-c0c1ad479aee?auto=format&fit=crop&q=95&w=1800',imageAlt:'Enterprise network switches and managed equipment'},
  {title:'Structured Cabling',description:'Standards-compliant copper and fibre cabling systems, tested and documented.',image:'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=95&w=1800',imageAlt:'Structured network cabling in an equipment installation'},
  {title:'Wireless Infrastructure',description:'Reliable enterprise Wi-Fi designed for coverage, capacity and secure access.',image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=95&w=1800',imageAlt:'Wireless communications and connected network hardware'},
  {title:'Data Centres',description:'Server-room and data-centre infrastructure with dependable power, cooling and connectivity.',image:'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=95&w=1800',imageAlt:'Enterprise data-centre server racks'},
  {title:'Cloud Integration',description:'Secure cloud connectivity, backup and business continuity solutions.',image:'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=95&w=1800',imageAlt:'Global digital connectivity supporting cloud integration'},
  {title:'Managed ICT Services',description:'Monitoring, preventive maintenance and technical support for dependable operations.',image:'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=95&w=1800',imageAlt:'ICT team providing managed technology support'},
];
export default function ICT(){return <><PageHero badge="ICT INFRASTRUCTURE" title="Digital Infrastructure That Performs." description="Enterprise networking, fibre optics, structured cabling, wireless and data centres."/><section className="section bg-[#F8FAFC]"><div className="container"><SectionHeader badge="CAPABILITIES" title="ICT Infrastructure" description="Secure, scalable systems that connect people, facilities and mission-critical operations." center/><CapabilityGrid items={items}/></div></section></>}
