import PageHero from '@/components/ui/PageHero'; import SectionHeader from '@/components/ui/SectionHeader'; import CapabilityGrid,{Capability} from '@/components/ui/CapabilityGrid';
const items:Capability[]=[
  {title:'Feasibility Studies',description:'Technical and commercial assessments that establish an informed project path.',image:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=95&w=1800',imageAlt:'Project team reviewing an infrastructure proposal'},
  {title:'Engineering Design',description:'Concept-to-detail design for safe, compliant and efficient infrastructure.',image:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=95&w=1800',imageAlt:'Engineering design and technical planning'},
  {title:'Procurement Support',description:'Technical specifications, vendor evaluation and equipment selection support.',image:'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&q=95&w=1800',imageAlt:'Technical procurement team coordinating project requirements'},
  {title:'Project Management',description:'Planning, risk management, coordination and disciplined project delivery.',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=95&w=1800',imageAlt:'Project management team coordinating delivery'},
  {title:'Construction Supervision',description:'Site supervision, inspection and quality assurance through execution.',image:'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=95&w=1800',imageAlt:'Construction-site supervision and infrastructure delivery'},
  {title:'Technical Advisory',description:'Independent expert support for complex infrastructure decisions and assurance.',image:'https://images.unsplash.com/photo-1581092919535-7146ff1a590a?auto=format&fit=crop&q=95&w=1800',imageAlt:'Engineering expert providing technical advice'},
];
export default function Engineering(){return <><PageHero badge="ENGINEERING CONSULTANCY" title="Engineering Expertise From Concept To Completion." description="Engineering design, project management, feasibility studies and technical advisory."/><section className="section bg-[#F8FAFC]"><div className="container"><SectionHeader badge="CAPABILITIES" title="Engineering Consultancy" description="Professional guidance and technical control throughout the infrastructure lifecycle." center/><CapabilityGrid items={items}/></div></section></>}
