import PageHero from '@/components/ui/PageHero'; import SectionHeader from '@/components/ui/SectionHeader'; import CapabilityGrid,{Capability} from '@/components/ui/CapabilityGrid';
import { createPageMetadata } from '@/lib/seo';
export const metadata = createPageMetadata({ title: 'Engineering Consultancy', description: 'GNIT provides engineering design, feasibility studies, project management, procurement, construction supervision and commissioning support.', path: '/services/engineering', keywords: ['engineering consultancy Nigeria', 'project management Nigeria', 'construction supervision', 'EPC consultancy'] });
const items:Capability[]=[
  {title:'Feasibility Studies',description:'Technical and commercial assessments that establish an informed project path.',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=95&w=1800',imageAlt:'Project team evaluating technical and commercial options'},
  {title:'Engineering Design',description:'Concept-to-detail design for safe, compliant and efficient infrastructure.',image:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=95&w=1800',imageAlt:'Engineer preparing detailed drawings and design documentation'},
  {title:'Procurement Support',description:'Technical specifications, vendor evaluation and equipment selection support.',image:'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&q=95&w=1800',imageAlt:'Technical procurement team coordinating project requirements'},
  {title:'Project Management',description:'Planning, risk management, coordination and disciplined project delivery.',image:'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=95&w=1800',imageAlt:'Project team coordinating an infrastructure delivery plan'},
  {title:'Construction Supervision',description:'Site supervision, inspection and quality assurance through execution.',image:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=95&w=1800',imageAlt:'Construction team carrying out site supervision and delivery'},
  {title:'Technical Advisory',description:'Independent expert support for complex infrastructure decisions and assurance.',image:'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=95&w=1800',imageAlt:'Technical team collaborating on an infrastructure advisory assignment'},
];
export default function Engineering(){return <><PageHero badge="ENGINEERING CONSULTANCY" title="Engineering Expertise From Concept To Completion." description="Engineering design, project management, feasibility studies and technical advisory."/><section className="section bg-[#F8FAFC]"><div className="container"><SectionHeader badge="CAPABILITIES" title="Engineering Consultancy" description="Professional guidance and technical control throughout the infrastructure lifecycle." center/><CapabilityGrid items={items}/></div></section></>}
