import PageHero from '@/components/ui/PageHero'; import SectionHeader from '@/components/ui/SectionHeader'; import CapabilityGrid,{Capability} from '@/components/ui/CapabilityGrid';
const items:Capability[]=[
  {title:'Video Surveillance',description:'Enterprise CCTV systems, video management and intelligent monitoring.',image:'https://images.unsplash.com/photo-1572044727169-8b7dda92916e?auto=format&fit=crop&q=95&w=1800',imageAlt:'Professional CCTV camera monitoring a facility'},
  {title:'Access Control',description:'Secure access control for people, vehicles and protected areas.',image:'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&q=95&w=1800',imageAlt:'Secure digital access and authentication system'},
  {title:'Visitor Management',description:'Controlled visitor registration, access permissions and audit trails for facilities.',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=95&w=1800',imageAlt:'Professional reception and visitor management'},
  {title:'Perimeter Protection',description:'Layered perimeter detection, electric fencing and secure-site design.',image:'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=95&w=1800',imageAlt:'Industrial facility perimeter requiring layered protection'},
  {title:'Intrusion Detection',description:'Integrated alarm systems that detect and communicate threats quickly.',image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=95&w=1800',imageAlt:'Digital security monitoring and intrusion alert technology'},
  {title:'Command & Control',description:'Centralised security operations and visibility across connected systems.',image:'https://images.unsplash.com/photo-1708807472445-d33589e6b090?auto=format&fit=crop&q=95&w=1800',imageAlt:'Security operations controller monitoring a multi-screen control room'},
  {title:'Maintenance & Support',description:'Preventive servicing and responsive support for reliable security operations.',image:'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&q=95&w=1800',imageAlt:'Field technician inspecting security infrastructure'},
];
export default function Security(){return <><PageHero badge="ELECTRONIC SECURITY" title="Security Systems That Protect What Matters." description="CCTV, access control, perimeter protection and command-centre solutions."/><section className="section bg-[#F8FAFC]"><div className="container"><SectionHeader badge="CAPABILITIES" title="Electronic Security" description="Integrated security technology that protects people, assets and critical facilities." center/><CapabilityGrid items={items}/></div></section></>}
